### PR TITLE
Put attribution control at the bottom of the lower-right control stack

### PR DESCRIPTION
**Pull request by iandees**
For https://github.com/openaddresses/batch/pull/392#issuecomment-2181831358

### CODE REVIEW

**Comment by mnalis** [comment]
It this supposed to be live on the map by now?

It still looks broken to me at e.g. https://batch.openaddresses.io/location/862#map=5.19/44.518/16.455

**Comment by iandees** [comment]
It should be. I think something needs to get deployed to update the code. I'll try to remember how that works.

**Comment by ingalls** [comment]
@iandees I'll deploy now

**Comment by ingalls** [comment]
```
deploy update prod```

**Comment by mnalis** [comment]
Looks good now!

**Comment by iandees** [comment]
Thanks for the reminder, Nick!

**Pull request merged**
