### PR TITLE
Unified Schema

### PR DESCRIPTION
**Pull request by ingalls**
### Context

Use a unified schema location to avoid the schemas diverging between batch and the OA repo

Ref: https://github.com/openaddresses/batch/pull/82

### CODE REVIEW

**Comment by macieg** [comment]
I'm not sure if it solved the actual problem. What steps should I take in order to change the schema and see correct results in the CI run?
I've changed the schema [here](https://github.com/openaddresses/openaddresses/pull/4987). 

If I understand correctly, now the batch process needs a released version of openaddresses. If I want to succeed I should change the schema first (without any code changes). Then release a new version with changed schema. Then update openaddresses version in batch repo (2.0.2 -> 2.0.3 probably).

Is it correct?

**Comment by macieg** [comment]
@ingalls ping

**Comment by ingalls** [comment]
@macieg Sorry, work took over, just getting back to catching up on OA stuff. Yes, if you can make a schema only PR in openaddresses (no data source changes) I'll get that merged and then we can update the version here & deploy. And then make a subsequent data change.

**Comment by macieg** [comment]
@ingalls here it is -> the schema only PR https://github.com/openaddresses/openaddresses/pull/5451

**Pull request merged**
